name: Test

on:
  pull_request:
  push:
    branches: [main]

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
